real:
  kernel: aexpon
  eps: 0.01
  #nu: 10
  nu: 1
  alpha: 0.5
  gammap: [3,3]
  gammal: [5,300]
  prop_bwsp: [0.005, 0.05, 0.005, 0.05]
  #prop_bwsp: [0.005, 0.05, 0.05, 0.05]
  vplus: 10
  #stable: True

jump2:
  kernel: aexpon
  eps: 0.1
  nu: 1
  #alpha: 0.5
  gammap: [3,3]
  gammal: [5,300]
  prop_bwsp: [0.1, 0.05, 0.05, 0.05]
  vplus: 10
  #stable: True
  #
jump:
  kernel: aexpon
  eps: 0.1
  nu: 1
  #alpha: 0.5
  gammap: [3,3]
  gammal: [5,300]
  prop_bwsp: [0.1, 0.05, 0.05, 0.05]
  vplus: 10
  #stable: True

sigt:
  kernel: expon
  eps: 0.1
  nu: 1
  gammap: [4,4]
  gammal: [5,300]
  prop_bwsp: [0.1, 0.05, 0.05, 0.05]
  vplus: 10
