real:
  kernel: aexpon
  eps: 0.01
  #nu: 10
  nu: 1
  gammap: [3,3]
  gammal: [5,300]
  prop_bwsp: [0.005, 0.05, 0.05, 0.05]
  vplus: 10

jump:
  kernel: aexpon
  eps: 0.1
  nu: 1
  gammap: [3,3]
  gammal: [5,300]
  prop_bwsp: [0.1, 0.05, 0.05, 0.05]
  vplus: 10

sigt:
  kernel: expon
  eps: 0.1
  nu: 1
  gammap: [4,4]
  gammal: [5,300]
  prop_bwsp: [0.1, 0.05, 0.05, 0.05]
  vplus: 10
